name: deploy

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: docker log in
        run: echo "${{secrets.DOCKER_PASSWORD}}" | docker login -u "${{secrets.DOCKER_USERNAME}}" --password-stdin

      - name: build and deploy image
        shell: bash
        run: |
          docker build -t eesast/overleaf-base:latest -f Dockerfile-base .
          docker build -t eesast/overleaf:latest .
          docker push eesast/overleaf:latest
